### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Kurosama** [ramonvictor/tic-tac-toe-js#5]
- Chrome it's ok .
- In Firefox cell selection does not work for the player X. I selected the 3 boxes at the top and this is the result.
  ![error_for_github](https://cloud.githubusercontent.com/assets/2848238/15067357/fbb121a8-136f-11e6-953a-5db2a2a889cc.png)
- doesm't work in IE 11

**Comment by ramonvictor** [comment]
@Kurosama thanks for spotting the issue. I'll fix this as soon as possible.

**Comment by ramonvictor** [comment]
Hi @Kurosama, I've just released this patch (0aa7919ad25b5e4671febcff83413845c28d8dc1) that should fix Firefox and IE issues. Could you double check whether it's working properly on IE11?

**Comment by Kurosama** [comment]
Firefox works correctly.
In IE11 I don't understand why not work apart from the room selection.
There isn't the possibility to select the cells and don't returns javascript error.
In the evening I will check the problem and update the issue

**Comment by ramonvictor** [comment]
@Kurosama today I have access to windows machines, so I'll do a quick round of testing and try to figure out what's going on there. If you have any more details, just let me know. Thanks for your help!

**Comment by ramonvictor** [comment]
So, these two commits ca9e36b16b07797cdd15e54d6dc81a1d7f5688e5 and 9465e606684f69b533042421379ef08f6cb3f004 fixes the errors on IE10/IE11. I don't plan to support earlier versions for now, so I'll close the issue. Thanks for your report, @Kurosama! :)
